app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView

from . import views

app_name = "app"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "login/",
        views.LoginView.as_view(template_name="login.html"),
        name="login",
    ),
    path("posts/", views.post_list_view, name="posts"),
]


htmx_urlpatterns = [
    path("check_email/", views.check_email, name="check_email"),
    path("add_post/", views.add_post, name="add_post"),
    path("delete_post/<int:post_id>/", views.delete_post, name="delete_post"),
]


urlpatterns += htmx_urlpatterns

namster/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("app/", view=include("app.urls")),
    path("admin/", admin.site.urls),
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import BaseUserManager


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_staff", True)
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []


class Post(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from app.models import User, Post


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "password1", "password2"]


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]

app/views.py
from django.http import HttpResponse
from django.http.response import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import FormView, TemplateView, ListView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib.auth import get_user_model
from .forms import RegisterForm, PostForm
from .models import Post
from django.shortcuts import render
from django.http import Http404
from django.core.exceptions import PermissionDenied


class IndexView(TemplateView):
    template_name = "index.html"


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = "register.html"
    success_url = reverse_lazy("app:login")

    def form_valid(self, form):
        form.save()  # save the user
        return super().form_valid(form)


def check_email(request):
    email = request.POST.get("email")
    if get_user_model().objects.filter(email=email).exists():
        return HttpResponse(
            "<div id='email-error' class='error'>This email already exists</div>"
        )
    else:
        return HttpResponse(
            "<div id='email-error' class='success'>This email is available</div>"
        )


@login_required
def post_list_view(request):
    posts = Post.objects.filter(user=request.user).order_by("-date_posted")
    form = PostForm()
    context = {
        "posts": posts,
        "form": form,
    }
    return render(request, "posts.html", context)


@require_http_methods(["POST"])
@login_required
def add_post(request):
    form = PostForm(request.POST)
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
    return render(
        request,
        "partials/post_list.html",
        context={
            "posts": Post.objects.filter(user=request.user).order_by("-date_posted")
        },
    )


@require_http_methods(["DELETE"])
@login_required
def delete_post(request, post_id):
    try:
        post = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        raise Http404("Post does not exist")

    if post.user != request.user:
        raise PermissionDenied("You are not allowed to delete this post")

    post.delete()
    return render(
        request,
        "partials/post_list.html",
        context={
            "posts": Post.objects.filter(user=request.user).order_by("-date_posted")
        },
    )

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App</title>


    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
</head>
<body>
    {% include 'partials/navbar.html' %}

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
    
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<p>Welcome!</p>

{% lorem 2 p %}

{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}


<div>
    <p>Login</p>
    <hr/>
    <form method="POST" action="{% url 'app:login' %}" autocomplete="off">
        {% csrf_token %}

        {% for field in form %}
        <div class>
            <label>{{ field.label_tag }}</label>
            {{ field.errors }}
            {% render_field field placeholder=field.name %}
        </div>
        {% endfor %}
        
        <button type="submit">Login</button>
        {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
        {% endif %}
    </form>
</div>

{% endblock content %}

app/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'app:index' %}">App</a>

    <div id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="">{{ user.email }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:posts' %}">Posts</a>
            </li>
            <form method="post" action="{% url 'app:logout' %}">
                {% csrf_token %}
                <button type="submit">logout</button>
            </form>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:register' %}">Register</a>
            </li>
            {% endif %}

        </ul>
    </div>
</nav>

app/templates/partials/post_list.html
{% for post in posts %}
    <div class="post">
        <h2>{{ post.title }}</h2>
        <p>{{ post.content }}</p>
        <p>Author: {{ post.user }}</p>
        <button hx-delete="{% url 'app:delete_post' post.id %}" hx-target="#post_list" hx-confirm="are you sure?">Delete</button>
    </div>
{% empty %}
    <p>No posts available.</p>
{% endfor %}

app/templates/posts.html
{% extends 'base.html' %}

{% block content %}
<div>
    <div>
        <p class>My posts</p>
    </div>

    <div id="post_list">
        {% include 'partials/post_list.html' %}
    </div>

    <hr/>

    <div>
        <form>
            {% csrf_token %}
            {{ form }}
            <button hx-post={% url 'app:add_post' %} hx-target="#post_list" type="submit">Add post</button>
        </form>
    </div>
</div>
{% endblock content %}

app/templates/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div>
    <p>Register</p>
    <hr/>
    <form method="POST" action="{% url 'app:register' %}" autocomplete='off'>
        {% csrf_token %}

        <div>
            <label>{{ form.email.label_tag }}</label>
            {{ form.email.errors }}
            {% url 'app:check_email' as check_email_url %}
            {% render_field form.email type="email" hx-post=check_email_url hx-triggers="keyup changed delay:2s" hx-target="#email-error" hx-swap="outerHTML"%}
            <div id='email-error'></div>

            <br/>
            <label>{{ form.password1.label_tag }}</label>
            {{ form.password1.errors }}
            {% render_field form.password1 %}

            <label>{{ form.password2.label_tag }}</label>
            {{ form.password2.errors }}
            {% render_field form.password2 %}
        </div>
        
        <button type="submit">Register</button>
    </form>
</div>
{% endblock content %}